### ISSUE TITLE
Cannot install/edit new configuration Atom Echo M5 anymore

### ISSUE THREAD

**Issue by xteaun** [esphome/firmware#76] opened 2023-10-23 16:15 UTC
I just wanted to update the yaml-file of my working Atom Echo M5. It does not work anymore. Am I doing something wrong? Is this a bug? I am running the latest version of Home Assistant on a Rhaspberry 4 with the ESPHome-beta-AddOn.

Christian

```
INFO ESPHome 2023.10.1
INFO Reading configuration /config/esphome/m5stack-atom-echo-8a1468.yaml...
INFO Updating https://github.com/esphome/esphome.git@pull/5230/head
INFO Generating C++ source...
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 33, in <module>
    sys.exit(load_entry_point('esphome', 'console_scripts', 'esphome')())
  File "/esphome/esphome/__main__.py", line 1036, in main
    return run_esphome(sys.argv)
  File "/esphome/esphome/__main__.py", line 1023, in run_esphome
    rc = POST_CONFIG_ACTIONS[args.command](args, config)
  File "/esphome/esphome/__main__.py", line 454, in command_run
    exit_code = write_cpp(config)
  File "/esphome/esphome/__main__.py", line 190, in write_cpp
    return write_cpp_file()
  File "/esphome/esphome/__main__.py", line 208, in write_cpp_file
    writer.write_cpp(code_s)
  File "/esphome/esphome/writer.py", line 342, in write_cpp
    copy_src_tree()
  File "/esphome/esphome/writer.py", line 295, in copy_src_tree
    copy_files()
  File "/esphome/esphome/components/esp32/__init__.py", line 593, in copy_files
    repo_dir, _ = git.clone_or_update(
  File "/esphome/esphome/git.py", line 95, in clone_or_update
    old_sha = run_git_command(["git", "rev-parse", "HEAD"], str(repo_dir))
  File "/esphome/esphome/git.py", line 32, in run_git_command
    raise cv.Invalid(err_str)
voluptuous.error.Invalid: fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**Comment by GrumpyMeow** [comment] 2023-10-24 15:37
My compilation issues were resolved by choosing "Clean Build Files" and then retry-ing.

**Comment by jesserockz** [comment] 2023-10-25 19:44
A few people have seen this error pop up. I feel like its a network/storage error that corrupts the local files that are cached. I have not seen it myself yet so I cannot debug it and try to fix.

As its not a bug specific to the firmware repo I am going to close this issue.

**Closed by jesserockz** 2023-10-25 19:44 UTC
